name: CI

on:
  push:
    branches: [ "master", "main", "develop" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Run tests
        env:
          NODE_ENV: test
          # Si ton app lit host/port via conf/default.json -> OK.
          # Sinon, ajoute ici les variables attendues par ton configure()
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: npm test
